export const QueryKeys = {
  LIST_PRODUCTS: "LIST_PRODUCTS",
  CREATE_PRODUCT: "CREATE_PRODUCT",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  GET_PRODUCT_ID: "GET_PRODUCT_ID",
};
